version: '3.5'

services:
  check_obituaries:
    container_name: check_obituaries
    image: 'check_obituaries/check_obituaries:latest'
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      TZ: America/Los_Angeles
      EMAIL_FROM: '${FROM_EMAIL}'
      EMAIL_TO: '${TO_EMAIL}'
      EMAIL_GREETING: '${EMAIL_GREETING}'
      SMTP_URL: '${SMTP_URL}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_EMAIL: '${SMTP_EMAIL}'
      SMTP_PASSWORD: '${SMTP_PASSWORD}'
      LAST_NAMES: '${LAST_NAMES}'
