version: "3.5"

services:
  check_obituaries_alert:
    container_name: check_obituaries_alert
    image: ghcr.io/littlehoushontheprairie/check_obituaries_alert:latest
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      TZ: America/Los_Angeles
      FROM_EMAIL: "${FROM_EMAIL}"
      TO_NAME: "${TO_NAME}"
      TO_EMAIL: "${TO_EMAIL}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
    volumes:
      - /path/to/data:/data
  
